// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf C++ Version: 5.29.3

#include "data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dev {
namespace jasser {
namespace configDaemon {

inline constexpr UdsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        statuscode_{0},
        type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UdsResponse::UdsResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UdsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UdsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UdsResponseDefaultTypeInternal() {}
  union {
    UdsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UdsResponseDefaultTypeInternal _UdsResponse_default_instance_;

inline constexpr UdsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UdsRequest::UdsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UdsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UdsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UdsRequestDefaultTypeInternal() {}
  union {
    UdsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UdsRequestDefaultTypeInternal _UdsRequest_default_instance_;
}  // namespace configDaemon
}  // namespace jasser
}  // namespace dev
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_data_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_data_2eproto = nullptr;
const ::uint32_t
    TableStruct_data_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsRequest, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsRequest, _impl_.key_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsResponse, _impl_.statuscode_),
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsResponse, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::dev::jasser::configDaemon::UdsResponse, _impl_.type_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dev::jasser::configDaemon::UdsRequest)},
        {10, -1, -1, sizeof(::dev::jasser::configDaemon::UdsResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dev::jasser::configDaemon::_UdsRequest_default_instance_._instance,
    &::dev::jasser::configDaemon::_UdsResponse_default_instance_._instance,
};
const char descriptor_table_protodef_data_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ndata.proto\022\027dev.jasser.configDaemon\"\'\n"
    "\nUdsRequest\022\014\n\004type\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\">"
    "\n\013UdsResponse\022\022\n\nstatusCode\030\001 \001(\005\022\r\n\005val"
    "ue\030\002 \001(\t\022\014\n\004type\030\003 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_data_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_data_2eproto = {
    false,
    false,
    150,
    descriptor_table_protodef_data_2eproto,
    "data.proto",
    &descriptor_table_data_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_data_2eproto::offsets,
    file_level_enum_descriptors_data_2eproto,
    file_level_service_descriptors_data_2eproto,
};
namespace dev {
namespace jasser {
namespace configDaemon {
// ===================================================================

class UdsRequest::_Internal {
 public:
};

UdsRequest::UdsRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dev.jasser.configDaemon.UdsRequest)
}
inline PROTOBUF_NDEBUG_INLINE UdsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dev::jasser::configDaemon::UdsRequest& from_msg)
      : type_(arena, from.type_),
        key_(arena, from.key_),
        _cached_size_{0} {}

UdsRequest::UdsRequest(
    ::google::protobuf::Arena* arena,
    const UdsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UdsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:dev.jasser.configDaemon.UdsRequest)
}
inline PROTOBUF_NDEBUG_INLINE UdsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : type_(arena),
        key_(arena),
        _cached_size_{0} {}

inline void UdsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UdsRequest::~UdsRequest() {
  // @@protoc_insertion_point(destructor:dev.jasser.configDaemon.UdsRequest)
  SharedDtor(*this);
}
inline void UdsRequest::SharedDtor(MessageLite& self) {
  UdsRequest& this_ = static_cast<UdsRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.type_.Destroy();
  this_._impl_.key_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UdsRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UdsRequest(arena);
}
constexpr auto UdsRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UdsRequest),
                                            alignof(UdsRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UdsRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UdsRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UdsRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UdsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UdsRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UdsRequest>(), &UdsRequest::ByteSizeLong,
            &UdsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UdsRequest, _impl_._cached_size_),
        false,
    },
    &UdsRequest::kDescriptorMethods,
    &descriptor_table_data_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UdsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2> UdsRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dev::jasser::configDaemon::UdsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string key = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UdsRequest, _impl_.key_)}},
    // string type = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UdsRequest, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string type = 1;
    {PROTOBUF_FIELD_OFFSET(UdsRequest, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string key = 2;
    {PROTOBUF_FIELD_OFFSET(UdsRequest, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\4\3\0\0\0\0\0"
    "dev.jasser.configDaemon.UdsRequest"
    "type"
    "key"
  }},
};

PROTOBUF_NOINLINE void UdsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dev.jasser.configDaemon.UdsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  _impl_.key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UdsRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UdsRequest& this_ = static_cast<const UdsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UdsRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UdsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dev.jasser.configDaemon.UdsRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string type = 1;
          if (!this_._internal_type().empty()) {
            const std::string& _s = this_._internal_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dev.jasser.configDaemon.UdsRequest.type");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string key = 2;
          if (!this_._internal_key().empty()) {
            const std::string& _s = this_._internal_key();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dev.jasser.configDaemon.UdsRequest.key");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dev.jasser.configDaemon.UdsRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UdsRequest::ByteSizeLong(const MessageLite& base) {
          const UdsRequest& this_ = static_cast<const UdsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UdsRequest::ByteSizeLong() const {
          const UdsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dev.jasser.configDaemon.UdsRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string type = 1;
            if (!this_._internal_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_type());
            }
            // string key = 2;
            if (!this_._internal_key().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_key());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UdsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UdsRequest*>(&to_msg);
  auto& from = static_cast<const UdsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dev.jasser.configDaemon.UdsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UdsRequest::CopyFrom(const UdsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dev.jasser.configDaemon.UdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UdsRequest::InternalSwap(UdsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
}

::google::protobuf::Metadata UdsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UdsResponse::_Internal {
 public:
};

UdsResponse::UdsResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dev.jasser.configDaemon.UdsResponse)
}
inline PROTOBUF_NDEBUG_INLINE UdsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dev::jasser::configDaemon::UdsResponse& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

UdsResponse::UdsResponse(
    ::google::protobuf::Arena* arena,
    const UdsResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UdsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, statuscode_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, statuscode_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, statuscode_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:dev.jasser.configDaemon.UdsResponse)
}
inline PROTOBUF_NDEBUG_INLINE UdsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void UdsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, statuscode_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, statuscode_) +
               sizeof(Impl_::type_));
}
UdsResponse::~UdsResponse() {
  // @@protoc_insertion_point(destructor:dev.jasser.configDaemon.UdsResponse)
  SharedDtor(*this);
}
inline void UdsResponse::SharedDtor(MessageLite& self) {
  UdsResponse& this_ = static_cast<UdsResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UdsResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UdsResponse(arena);
}
constexpr auto UdsResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UdsResponse),
                                            alignof(UdsResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UdsResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UdsResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UdsResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UdsResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UdsResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UdsResponse>(), &UdsResponse::ByteSizeLong,
            &UdsResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_._cached_size_),
        false,
    },
    &UdsResponse::kDescriptorMethods,
    &descriptor_table_data_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UdsResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 49, 2> UdsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dev::jasser::configDaemon::UdsResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 statusCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UdsResponse, _impl_.statuscode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.statuscode_)}},
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.value_)}},
    // int32 type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UdsResponse, _impl_.type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 statusCode = 1;
    {PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.statuscode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 type = 3;
    {PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\43\0\5\0\0\0\0\0"
    "dev.jasser.configDaemon.UdsResponse"
    "value"
  }},
};

PROTOBUF_NOINLINE void UdsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:dev.jasser.configDaemon.UdsResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  ::memset(&_impl_.statuscode_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.statuscode_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UdsResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UdsResponse& this_ = static_cast<const UdsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UdsResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UdsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dev.jasser.configDaemon.UdsResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 statusCode = 1;
          if (this_._internal_statuscode() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_statuscode(), target);
          }

          // string value = 2;
          if (!this_._internal_value().empty()) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dev.jasser.configDaemon.UdsResponse.value");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 type = 3;
          if (this_._internal_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dev.jasser.configDaemon.UdsResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UdsResponse::ByteSizeLong(const MessageLite& base) {
          const UdsResponse& this_ = static_cast<const UdsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UdsResponse::ByteSizeLong() const {
          const UdsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dev.jasser.configDaemon.UdsResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string value = 2;
            if (!this_._internal_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
            // int32 statusCode = 1;
            if (this_._internal_statuscode() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_statuscode());
            }
            // int32 type = 3;
            if (this_._internal_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UdsResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UdsResponse*>(&to_msg);
  auto& from = static_cast<const UdsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dev.jasser.configDaemon.UdsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_statuscode() != 0) {
    _this->_impl_.statuscode_ = from._impl_.statuscode_;
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UdsResponse::CopyFrom(const UdsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dev.jasser.configDaemon.UdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UdsResponse::InternalSwap(UdsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.type_)
      + sizeof(UdsResponse::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(UdsResponse, _impl_.statuscode_)>(
          reinterpret_cast<char*>(&_impl_.statuscode_),
          reinterpret_cast<char*>(&other->_impl_.statuscode_));
}

::google::protobuf::Metadata UdsResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace configDaemon
}  // namespace jasser
}  // namespace dev
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_data_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
